# Generated by Django 2.1.3 on 2018-11-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('merchant_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Merchant_Management.CreateMerchant')),
                ('address', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('contact_number', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('RED', 'Just Save'), ('WHITE', 'Request for Pickup')], default='RED', max_length=100)),
            ],
        ),
    ]
