# Generated by Django 2.1.3 on 2018-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='action',
            field=models.CharField(choices=[('Queue', 'Just Save'), ('Pickup Request', 'Request for Pickup')], default='Queue', max_length=100),
        ),
    ]
