# Generated by Django 2.1.4 on 2018-12-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Ambassador', '0002_createambassador_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createambassador',
            name='complete',
        ),
    ]
