# Generated by Django 2.1.3 on 2018-11-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': False},
        ),
    ]
