# Generated by Django 2.1.3 on 2018-11-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up', '0002_auto_20181128_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
    ]
