# Generated by Django 2.1.4 on 2018-12-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up', '0003_auto_20181128_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
