# Generated by Django 2.1.3 on 2018-11-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hub_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('assigned_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub_Management.CreateHubManager')),
            ],
        ),
    ]
