# Generated by Django 2.1.3 on 2018-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmanager',
            name='order_id',
            field=models.IntegerField(default=2),
        ),
    ]
