# Generated by Django 2.1.3 on 2018-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_auto_20181110_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubmanager',
            name='order',
            field=models.CharField(default='#', max_length=120),
        ),
    ]
