# Generated by Django 2.1.3 on 2018-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('contact_number', models.CharField(max_length=100)),
            ],
        ),
    ]
