# Generated by Django 2.1.3 on 2018-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Merchant', '0002_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='product_details',
            field=models.TextField(),
        ),
    ]
